import sys
from math import log

n_grams={}
#populate n_grams
with open("ngrams.txt") as f:
    for line in f:
        line=line.strip()
        segment,number=line.split(" ")
        n_grams[segment]=int(number)

message="ICALLOURWORLDMLATLANDNOTFECAUSEWECALLITSOFUTTOBAKEITSNATURECLEARERTOYOUBYHAPPYREADERSWHOAREPRIVILEGEDTOLIVEINSPACEIBAGINEAVASTSHEETOMPAPERONWHICHSTRAIGHTLINESTRIANGLESSQUARESPENTAGONSHEXAGONSANDOTHERMIGURESINSTEADOMREBAININGMIXEDINTHEIRPLACESBOVEMREELYAFOUTONORINTHESURMACEFUTWITHOUTTHEPOWEROMRISINGAFOVEORSINKINGFELOWITVERYBUCHLIKESHADOWSONLYHARDWITHLUBINOUSEDGESANDYOUWILLTHENHAVEAPRETTYCORRECTNOTIONOMBYCOUNTRYANDCOUNTRYBENALASAMEWYEARSAGOISHOULDHAVESAIDBYUNIVERSEFUTNOWBYBINDHASFEENOPENEDTOHIGHERVIEWSOMTHINGS"
message2="YOUR FIRST EXAMPLE IS QUITE AN EASY EXAMPLE, I THINK. IT IS EASY BECAUSE THIS SENTENCE USES ALL TEN MOST COMMON WORDS IN ENGLISH: 'I HAVE TO BE A GOOD STUDENT IN THAT CLASS IN THE ROOM OF THAT TEACHER.'"

def test_fitness(n, code):
    sum=0
    for i in range(0,len(code)-n):
        fragment=code[i:i+n]
        if fragment.isalpha():
            freq=n_grams.get(fragment,0)
            if freq>0:
                sum+=log(freq,2)
    return sum

#print(test_fitness(5,message))
#print(test_fitness(5,message2))

print(len(message))