import sys
from math import log

n_grams={}
#populate n_grams
with open("ngrams.txt") as f:
    for line in f:
        line=line.strip()
        segment,number=line.split(" ")
        n_grams[segment]=int(number)

message="THEEVENINGSTARMUSTBEDROOPINGANDSHEDDINGHERSPARKLERDIMSONTHEPRAIRIEWHICHISZUSTBEFORETHECOMINGOFCOMPLETENIGHTTHATBLESSESTHEEARTHDARKENSALLRIVERSCUPSTHEPEAKSANDFOLDSTHEFINALSHOREINANDNOBODYNOBODYKNOWSWHATSGOINGTOHAPPENTOANYBODYBESIDESTHEFORLORNRAGSOFGROWINGOLDITHINKOFDEANMORIARTYIEVENTHINKOFOLDDEANMORIARTYTHEFATHERWENEVERFOUNDITHINKOFDEANMORIARTY"
message2="THEEVENINGSTARMUSTBEDROOPINGANDSHEDDINGHERSPARKLERDIMSONTHEPRAIRIEWHICHISJUSTBEFORETHECOMINGOFCOMPLETENIGHTTHATBLESSESTHEEARTHDARKENSALLRIVERSCUPSTHEPEAKSANDFOLDSTHEFINALSHOREINANDNOBODYNOBODYKNOWSWHATSGOINGTOHAPPENTOANYBODYBESIDESTHEFORLORNRAGSOFGROWINGOLDITHINKOFDEANMORIARTYIEVENTHINKOFOLDDEANMORIARTYTHEFATHERWENEVERFOUNDITHINKOFDEANMORIARTY"

def test_fitness(n, code):
    sum=0
    for i in range(0,len(code)-n):
        fragment=code[i:i+n]
        if fragment.isalpha():
            freq=n_grams.get(fragment,0)
            if freq>0:
                sum+=log(freq,4)
    return sum

N=5
print(test_fitness(N,message))
print(test_fitness(N,message2))

print(len(message))